pub struct State {
    pub time: [u8; 4],
    pub pressure: f32,
    pub temperature: f32,
    pub accel_x: f32,
    pub accel_y: f32,
    pub accel_z: f32,
    pub gyro_x: f32,
    pub gyro_y: f32,
    pub gyro_z: f32,
    pub mag_x: f32,
    pub mag_y: f32,
    pub mag_z: f32,
    pub mag_heading: f32,
    pub batt_voltage: f32,
    pub low_batt: bool,
    pub power_good: bool,
    pub charge_status: bool,
}
